from turtle import *
import turtle
# color('red', 'yellow')
# begin_fill()
# while True:
#     forward(200)
#     left(170)
#     if abs(pos()) < 1:
#         break
# end_fill()
# done()

# turtle.color("white", "black")
# turtle.begin_fill()
# turtle.circle(30)
# turtle.end_fill()
turtle.pencolor("#996515")
turtle.position()
turtle.setx(0)
turtle.position()
turtle.pensize(3)
turtle.circle(50)
turtle.up()
turtle.sety(50)
turtle.setx(30)
turtle.position()
turtle.down()
turtle.circle(10)
turtle.up()
turtle.sety(50)
turtle.setx(-30)
turtle.position()
turtle.down()
turtle.circle(10)
turtle.up()
turtle.sety(20)
turtle.setx(-20)
turtle.down()
turtle.forward(45)
turtle.up()
turtle.sety(-30)
turtle.setx(-65)
turtle.write("Current mood", font=("Arial", 16, "normal"))
turtle.hideturtle()
done()

# turtle.shape()

# turtle.shape("man")
# turtle.shape()
# done()